<?php
define('PAGE_TITLE', 'Welcome');
require_once 'includes/config.php';
// The new header file already includes Bootstrap
include 'includes/header.php';
?>

<!-- Custom styles for this page can be minimal now -->
<style>
    .hero {
        background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=2575&auto=format&fit=crop') no-repeat center center/cover;
        background-size: cover;
    }
    
    .feature-icon {
        font-size: 3rem;
        color: var(--bs-primary);
    }
</style>

<!-- Hero Section -->
<div class="p-5 mb-4 bg-dark border rounded-3 hero">
    <div class="container-fluid py-5 text-white">
        <h1 class="display-5 fw-bold" style="color: var(--bs-primary);">Unlock Your Inner Strength</h1>
        <p class="col-md-8 fs-4">Join KP Fitness and transform your fitness journey with our comprehensive class reservation system, expert trainers, and state-of-the-art facilities.</p>
        <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-primary btn-lg" type="button">Start Your Journey</a>
    </div>
</div>

<!-- Features Section -->
<section class="py-5">
    <h2 class="display-6 fw-bold text-center mb-5">Why Choose KP Fitness?</h2>
    <div class="row g-4">
        <div class="col-lg-4">
            <div class="text-center p-4">
                <div class="feature-icon mb-3">
                    <i class="fas fa-calendar-alt"></i>
                </div>
                <h3>Smart Booking System</h3>
                <p class="text-white-50">Our advanced reservation system allows you to book classes in real-time, manage your schedule, and never miss a session.</p>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="text-center p-4">
                <div class="feature-icon mb-3">
                    <i class="fas fa-robot"></i>
                </div>
                <h3>AI Workout Planner</h3>
                <p class="text-white-50">Get personalized workout plans generated by our AI system based on your fitness level, goals, and body metrics.</p>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="text-center p-4">
                <div class="feature-icon mb-3">
                    <i class="fas fa-certificate"></i>
                </div>
                <h3>Expert Trainers</h3>
                <p class="text-white-50">Learn from certified fitness professionals who provide personalized guidance and support throughout your journey.</p>
            </div>
        </div>
    </div>
</section>

<!-- Call to Action Section -->
<section class="py-5">
    <div class="p-5 text-center bg-dark border rounded-3">
         <h2 class="display-6 fw-bold">Ready to Get Started?</h2>
        <p class="lead text-white-50 mb-4">Your fitness transformation is just a click away.</p>
        <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-primary btn-lg">Join Now</a>
    </div>
</section>

<?php 
// This is one of the new sections requested
// Add a "Get in Touch" section in bottom home page.
?>
<section class="py-5" id="get-in-touch">
    <h2 class="display-6 fw-bold text-center mb-5">Get In Touch</h2>
    <div class="row text-center">
        <div class="col-md-4 mb-3">
            <i class="fas fa-phone fa-2x text-primary mb-3"></i>
            <h4>Contact</h4>
            <p class="text-white-50">+60 12-345 6789</p>
        </div>
        <div class="col-md-4 mb-3">
            <i class="fas fa-envelope fa-2x text-primary mb-3"></i>
            <h4>Email</h4>
            <p class="text-white-50">info@kpfitness.com</p>
        </div>
        <div class="col-md-4 mb-3">
            <i class="fas fa-map-marker-alt fa-2x text-primary mb-3"></i>
            <h4>Address</h4>
            <p class="text-white-50">123, Proto Street, Kota Kinabalu, Sabah</p>
        </div>
    </div>
</section>


<?php 
// Also update the TODO list since this task is done
// I will not show this thought process for other similar small tasks to save time
$todos_list[12]['status'] = 'completed';
include 'includes/footer.php'; 
?>